[package]
name = "OMR"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fhe = "0.1.0-beta.4"
fhe-util = "0.1.0-beta.4"
fhe-traits = "0.1.0-beta.4"
fhe-math = "0.1.0-beta.4"
rand = "0.8.5"
itertools = "0.10.5"
byteorder = "1.4.3"