[package]
name = "OMR"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fhe = { path = "/Users/janmajayamall/desktop/fhe.rs/crates/fhe" }
fhe-util = { path = "/Users/janmajayamall/desktop/fhe.rs/crates/fhe-util"}
fhe-traits = { path = "/Users/janmajayamall/desktop/fhe.rs/crates/fhe-traits"}
fhe-math = { path = "/Users/janmajayamall/desktop/fhe.rs/crates/fhe-math"}
rand = "0.8.5"
itertools = "0.10.5"
byteorder = "1.4.3"
rayon = "1.6.0"